### ISSUE TITLE
It's Not Working in Iphone...

### ISSUE THREAD

**Issue by bnagarjuna** [zeroCoder1/Epub-Reader#6]
It's not working in iPhone, please send iPhone Project....

**Comment by zeroCoder1** [comment]
It's really simple to make it work with the iphone, just copy all the code and add constraints to change it to the iphone frame. the code anyway stays the same. 
I can't 'send' you any code. All of it is here.

**Comment by zeroCoder1** [comment]
it works on iphone, there are some commented code, you might want to uncomment them and check what it does. the change was just a frame. Next time, please elaborate, what exactly the problem is. You can help and contribute to improve the code, instead just asking for me to 'send' it

**Comment by bnagarjuna** [comment]
It's working in iPhone really Good.But the frame Sizes are not fitted.please help me where it change the frame.....
![ios simulator screen shot 15-jun-2015 2 18 11 pm](https://cloud.githubusercontent.com/assets/6882234/8156369/d82872ec-1369-11e5-8d99-8d1fe4f344ea.png)

**Comment by zeroCoder1** [comment]
Ok which branch of the code are you working on. Why don't you delete everything you have and re-download the code. I have done a few changes and it should work now. Tested it already

**Comment by bnagarjuna** [comment]
It's working Good sir.Thank u so much sir...
